# Spara i: .github/workflows/pr-check.notifyslack.yml

# 1. Namnet på ditt workflow
name: .NET PR Check med Slack Notis

# 2. Triggers (När ska detta köras?)
on:
  pull_request:
    branches: [ main ] # Körs när en PR öppnas/uppdateras mot 'main'

# 3. Jobb (Vad ska göras?)
jobs:
  build-test-and-notify:
    runs-on: ubuntu-latest # Vilken typ av maskin som ska användas
    steps:
      
      # Steg 1: Checka ut koden från PR:n
      - name: Kassa ut koden
        uses: actions/checkout@v4

      # -----------------------------------------------------------------
      # Steg 2: Sätt upp, bygg och testa .NET 8
      # -----------------------------------------------------------------
      
      # Sätter upp rätt version av .NET SDK (i det här fallet 8.x)
      - name: Sätt upp .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Hålls automatiskt uppdaterad till senaste 8.x

      # Återställer alla NuGet-paket för specifik solution
      - name: Återställ dependencies (dotnet restore)
        run: dotnet restore ./src/StudyTeknik.sln
        # OBS: Sökvägen är nu specifik!

      # Bygger den specifika solution-filen
      - name: Bygg projektet (dotnet build)
        run: dotnet build ./src/StudyTeknik.sln --no-restore
        # Vi lägger till '--no-restore' för att det är snabbare,
        # eftersom vi redan har kört 'restore' i steget innan.

      # Kör alla tester som tillhör den specifika solution-filen
      - name: Kör tester (dotnet test)
        run: dotnet test ./src/StudyTeknik.sln --no-build
        # Vi lägger till '--no-build' eftersom vi redan har byggt.
        # Om testerna misslyckas, kommer detta steg att "misslyckas"
        # och 'job.status' blir 'failure'
      
      # -----------------------------------------------------------------

      # Steg 3: Skicka Slack-avisering
      # 'if: always()' ser till att detta steg ALLTID körs,
      # även om 'dotnet test' (eller annat steg) misslyckades.
      - name: Skicka Slack-avisering
        if: always() 
        uses: rtCamp/action-slack-notify@v2
        env:
          # Hämtar din secret som du lade till i GitHubs inställningar
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }} 

          # Sätter färgen baserat på om jobbet lyckades (good) eller misslyckades (danger)
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }} 
          
          # Anpassat meddelande för en .NET PR
          SLACK_TITLE: ".NET PR Check: ${{ job.status }}"
          SLACK_USERNAME: "GitHub Actions Bot"
          SLACK_MESSAGE: |
            En pull request för *.NET* av *${{ github.actor }}* fick statusen: *${{ job.status }}*
            Branch: `${{ github.head_ref }}`
            Repo: `${{ github.repository }}`
          SLACK_FOOTER: "Se ändringar: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
